########################################
# +----------------------------------+ #
# | UltimateGuiRepair made by Pulsi_ | #
# +----------------------------------+ #
########################################

Settings:
  # The main prefix of the plugin.
  Prefix: "&8[&a&lU&c&lG&9&lR&8] "

  Repair-Cost:
    # Choose between CONSTANT and LINEAR
    # If the repair type won't be recognized,
    # the LINEAR type will be chosen by default.
    Type: "LINEAR"
    Cost: 20

    Enchants:
      # For each enchant, the price will increase.
      Increase-Cost: true
      # The cost will increase by the 10% for each enchant.
      Percentage: 10


  # To avoid players from repairing more items per time, enable this.
  Singular-Repair: true

  # The sound played when the item has been repaired.
  Repair-Sound: "BLOCK_ANVIL_USE 5 1" # Sound Volume Pitch

Gui:
  # The title of the gui.
  Title: "&a&lUltimate&c&lGui&9&lRepair"

  # A cool feature to fill the gui with the selected item.
  Gui-Filler:
    # Enable or not this option.
    Enabled: true

    # The item options.
    Material: "GRAY_STAINED_GLASS_PANE"
    Displayname: "&f"
    Glowing: false

  Items:
    Cancel:
      Type: "NORMAL" # You can also remove that.
      Material: "RED_WOOL"
      Displayname: "&c&lCANCEL"
      Lore:
        - "&7Cancel and go back"
      Slot: 1
      Actions:
        - "[CLOSE]"

    Item-Displayer:
      Type: "CUSTOM"
      Custom-Item: "ITEM-DISPLAYER"
      Slot: 3

    Repair:
      Type: "NORMAL"
      Material: "GREEN_WOOL"
      Displayname: "&a&lREPAIR"
      Lore:
        - "&7Repair this item."
        - ""
        - "&7Cost: &c$%cost_formatted%"
      Slot: 5
      Glowing: true
      Actions:
        - "[REPAIR]"